### ISSUE TITLE
Refactor & clean up code base to restart the project

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/website#21]
@sidharthgehlot had started the project a while ago but got occupied with work midway, since then we've decided to restart the project right now.

For starters, the code base requires a thorough cleaning & refactoring before work on developing the minimal landing page (_refer to #20_) can start. There's already an open PR #13 which hasn't been updated in a while so that needs to be taken care of before it can be merged.

Doing this is a necessity if maintainability & scalability is a requirement.

TO-DO:

- [x] Create & move the necessary files/folders into a `src` directory (_refer to [next.js `src` directory](https://nextjs.org/docs/advanced-features/src-directory) for more info_). _([see #24](https://github.com/developersIndia/developersIndia.in/pull/24))_
- [x] Remove unnecessary packages & dependencies which aren't required to build a minimal landing page. _([see #23](https://github.com/developersIndia/developersIndia.in/pull/23))_
- [x] #25
- [x] Add `.editorconfig` & `.gitattributes` files for better cross-platform development practices. _([see #24](https://github.com/developersIndia/developersIndia.in/pull/24))_
- [x] #26
- [x] #27
- [x] #28

This thread will be updated (or reopened) if necessary until the first iteration of the minimal landing page is deployed.

**Comment by afkcodes** [comment]
lets close this.

**Comment by Jarmos-san** [comment]
> lets close this.

There's still some more work to be done which I'll take care of later on. Once that's complete, I'll close this issue thread.

**Comment by afkcodes** [comment]
yeah, we should close this thread i was trying to find the close button couldn't find it.

**Comment by Jarmos-san** [comment]
All tasks in the TODO list is complete, hence closing this thread for now.
